services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: grupo4/tech_challenge
    container_name: grupo4_tech_challenge_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/grupo4_db
      SPRING_DATASOURCE_USERNAME: grupo4_user
      SPRING_DATASOURCE_PASSWORD: grupo4_pass
    depends_on:
      - postgresql
    networks:
      - challenge_grupo4

  postgresql:
    image: postgres:15
    container_name: postgre_db_grupo4
    ports:
      - "5432:5432"
    volumes:
      - grupo4_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: grupo4_user
      POSTGRES_PASSWORD: grupo4_pass
      POSTGRES_DB: grupo4_db
    networks:
      - challenge_grupo4

volumes:
  grupo4_postgres_data:

networks:
  challenge_grupo4:
    driver: bridge
